### ISSUE TITLE
Add iods box parsing

### ISSUE THREAD

**Issue by abhibhag** [abhijeetbhagat/mp4box#1]
It goes something like this (from http://xhelmboyx.tripod.com/formats/mp4-layout.txt):
   * 8+ bytes optional initial object descriptor box
       = long unsigned offset + long ASCII text string 'iods'
    - NOTE: this was added in vers. 2 of spec
     -> 4 bytes version/flags = 8-bit hex version + 24-bit hex flags

     -> 1 byte file IOD type tag = 8-bit hex value 0x10
     -> 3 bytes extended descriptor type tag string = 3 * 8-bit hex value
       - types are Start = 0x80 ; End = 0xFE
       - NOTE: the extended start tags may be left out
     -> 1 byte descriptor type length = 8-bit unsigned length

       -> 2 bytes OD ID = 16-bit unsigned value
       -> 1 byte OD profile level = 8-bit unsigned value
       -> 1 byte scene profile level = 8-bit unsigned value
       -> 1 byte audio profile level = 8-bit unsigned value
       -> 1 byte video profile level = 8-bit unsigned value
       -> 1 byte graphics profile level = 8-bit unsigned value
         - NOTE: if level unused then set to 0xFF

     -> 1 byte ES ID included descriptor type tag = 8-bit hex value 0x0E
     -> 3 bytes extended descriptor type tag string = 3 * 8-bit hex value
       - types are Start = 0x80 ; End = 0xFE
       - NOTE: the extended start tags may be left out
     -> 1 byte descriptor type length = 8-bit unsigned length

       -> 4 bytes Track ID = 32-bit unsigned value
         - NOTE: refers to non-data system tracks

**Comment by abhijeetbhagat** [comment]
Closing this because of #6
